services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    user: root
    working_dir: /notebooks
    ports:
      - "38888:38888"
    volumes:
      - "$PWD/notebooks:/notebooks"
      - "$PWD/jupyter_config.py:/home/jovyan/.jupyter/jupyter_config.py"
    depends_on:
      - nginx
      - vaurien_delay
      - vaurien_error_delay

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/flags.conf:ro
      - $PWD/downloads:/flags:ro
    expose:
      - "8001"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8001

  vaurien_delay:
    image: clintsharp/vaurien:latest
    container_name: vaurien_delay
    volumes:
      - $PWD/vaurien_delay.sh:/root/vaurien_delay.sh
    expose:
      - "8002"
    entrypoint:
      - /bin/bash
      - /root/vaurien_delay.sh
    depends_on:
      - nginx

  vaurien_error_delay:
    image: clintsharp/vaurien:latest
    container_name: vaurien_error_delay
    volumes:
      - $PWD/vaurien_error_delay.sh:/root/vaurien_error_delay.sh
    expose:
      - "8003"
    entrypoint:
      - /bin/bash
      - /root/vaurien_error_delay.sh
    depends_on:
      - nginx
